Use CMD instead of ENTRYPOINT
Chia-Network/chia-docker pull request #77
Opened 2021-05-30 19:26 UTC by davidbarratt

2021-06-01 11:49 UTC, shamaevnn approved these changes

2021-06-01 21:01 UTC, justinengland commented
branch has conflicts. also, not 100% sure I agree with the idea that you must be able to run esoteric commands. Docker exec can drop you to shell on the container.

2021-06-01 21:13 UTC, davidbarratt commented
> branch has conflicts. also, not 100% sure I agree with the idea that you must be able to run esoteric commands. Docker exec can drop you to shell on the container.

I'll fix the conflicts. `docker exec` only works if it's currently running. What if I want to generate plots instead of startup a farmer? Should I just be able to execute the relevant `chia` command?

2021-06-01 21:15 UTC, justinengland commented
i would say that plotting from the container is at best a secondary concern. Not really a use case Id like to bake into the default setup. 

its easy enough imo to get into the container run time to start plotting. 

its a fair point. let me think through the orchestration changes I would need to make for GHA.

2021-09-15 00:40 UTC, cmmarslender requested changes
Looking through PRs today, and I think I do like how the accomplishes your goal of supporting chia commands without necessarily having chia running - Its a bit out of date with main, but if you can get it updated with latest changes from main and take a look at the proposed change below (and the associated problem with that `tail`) I can do some testing on the container this week to make sure it still works for all the existing cases.

2021-09-15 00:40 UTC, cmmarslender commented on docker-start.sh
> +tail -f ~/.chia/mainnet/log/debug.log
```suggestion
tail -f $CHIA_ROOT/log/debug.log
```

This file doesn't necessarily exist right away either - I just tested a build of this locally (with latest main merged in) and I'm getting:

```
...
Daemon not started yet
Starting daemon
chia_harvester: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
tail: cannot open '/root/.chia/mainnet/log/debug.log' for reading: No such file or directory
tail: no files remaining
```

Need to either go back to the previous `while true; ...` stuff, or else, maybe just `touch $CHIA_ROOT/log/debug.log` before trying to tail it

2021-09-15 18:19 UTC, cmmarslender commented
Closing in favor of #110 (includes these changes plus a few fixes and resolving conflicts)

2021-09-15 18:19 UTC, closed without merging