Add --no-install-recommends to Dockerfile
Chia-Network/chia-docker pull request #81
Opened 2021-06-02 05:09 UTC by Arderos

Adding --no-install-recommends cuts the container size almost in half while retaining all packages specified in Dockerfile

2021-09-14 21:43 UTC, Arderos commented
Guys?

2021-09-15 00:22 UTC, cmmarslender requested changes

2021-09-15 00:22 UTC, cmmarslender commented on Dockerfile
> +RUN DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y curl jq python3 ansible tar bash ca-certificates git openssl unzip wget
```suggestion
RUN DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y curl lsb-release python3 tar bash ca-certificates git openssl unzip wget python3-pip sudo acl build-essential python3-dev python3.8-venv python3.8-distutils python-is-python3 vim tzdata
```

Fails with just this change, due to lsb_release no longer being present, but I think the above suggestion fixes that + cleans up a few other unnecessary things

2021-09-15 16:00 UTC, cmmarslender approved these changes

2021-09-15 16:00 UTC, merged